<?php
return array (
  'ckm3u8' => 
  array (
    'status' => '1',
    'from' => 'ckm3u8',
    'show' => 'OK',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.52xd.tv/v/?url=',
    'sort' => '1030',
    'tip' => '无需安装任何插件',
    'id' => 'ckm3u8',
  ),
  'wlm3u8' => 
  array (
    'status' => '1',
    'from' => 'wlm3u8',
    'show' => '卧龙',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.52xd.tv/v/?url=',
    'sort' => '1020',
    'tip' => '无需安装任何插件',
    'id' => 'wlm3u8',
  ),
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '腾讯',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.52xd.tv/addons/jiexi/?url=',
    'sort' => '1010',
    'tip' => '无需安装任何插件',
    'id' => 'qq',
  ),
  'qiyi' => 
  array (
    'status' => '1',
    'from' => 'qiyi',
    'show' => '爱奇艺',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.52xd.tv/addons/jiexi/?url=',
    'sort' => '1009',
    'tip' => '无需安装任何插件',
    'id' => 'qiyi',
  ),
  'youku' => 
  array (
    'status' => '1',
    'from' => 'youku',
    'show' => '优酷',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.52xd.tv/addons/jiexi/?url=',
    'sort' => '1008',
    'tip' => '无需安装任何插件',
    'id' => 'youku',
  ),
  'mgtv' => 
  array (
    'status' => '1',
    'from' => 'mgtv',
    'show' => '芒果',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.52xd.tv/addons/jiexi/?url=',
    'sort' => '1007',
    'tip' => '无需安装任何插件',
    'id' => 'mgtv',
  ),
  'letv' => 
  array (
    'status' => '1',
    'from' => 'letv',
    'show' => '乐视',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.52xd.tv/addons/jiexi/?url=',
    'sort' => '1006',
    'tip' => '无需安装任何插件',
    'id' => 'letv',
  ),
  'sohu' => 
  array (
    'status' => '1',
    'from' => 'sohu',
    'show' => '搜狐',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.52xd.tv/addons/jiexi/?url=',
    'sort' => '1005',
    'tip' => '无需安装任何插件',
    'id' => 'sohu',
  ),
  'pptv' => 
  array (
    'status' => '1',
    'from' => 'pptv',
    'show' => 'PPTV',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.52xd.tv/addons/jiexi/?url=',
    'sort' => '1004',
    'tip' => '无需安装任何插件',
    'id' => 'pptv',
  ),
  'm1905' => 
  array (
    'status' => '1',
    'from' => 'm1905',
    'show' => '1905',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.52xd.tv/addons/jiexi/?url=',
    'sort' => '1003',
    'tip' => '无需安装任何插件',
    'id' => 'm1905',
  ),
  'migu' => 
  array (
    'status' => '1',
    'from' => 'migu',
    'show' => '咪咕',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.52xd.tv/addons/jiexi/?url=',
    'sort' => '1002',
    'tip' => '无需安装任何插件',
    'id' => 'migu',
  ),
  'wasu' => 
  array (
    'status' => '1',
    'from' => 'wasu',
    'show' => '华数',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.52xd.tv/addons/jiexi/?url=',
    'sort' => '1001',
    'tip' => '无需安装任何插件',
    'id' => 'wasu',
  ),
  'funshion' => 
  array (
    'status' => '1',
    'from' => 'funshion',
    'show' => '风行',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.52xd.tv/addons/jiexi/?url=',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'funshion',
  ),
  'ckplayerx' => 
  array (
    'status' => '1',
    'from' => 'ckplayerx',
    'show' => 'Ckplayer x 播放器',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '909',
    'tip' => '无需安装任何插件',
    'id' => 'ckplayerx',
  ),
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlay播放器',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'from' => 'videojs',
    'show' => 'videojs播放器',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '907',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'aliplayer' => 
  array (
    'status' => '1',
    'from' => 'aliplayer',
    'show' => '阿里云播放器',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '906',
    'tip' => '无需安装任何插件',
    'id' => 'aliplayer',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '904',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '903',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '902',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'flv' => 
  array (
    'status' => '1',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '901',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
);